### ISSUE TITLE
Make game relate to theme

### ISSUE THREAD

**Issue by remarkablemark** [remarkablegames/linkit#10]
## Problem

As a player, I want to make the game related to the theme `power` so that we can submit to the game jam.

## Suggested Solution

On level end, show an animated lightbulb in the middle of the screen as a fadeaway.

Compress image with https://compressor.io/

Emojis: 💡 ⚡

## Keywords

power,theme,animation,lightbulb

**Comment by rmacohen** [comment]
Using "Brainpower" instead of electricity, etc.
